#!/bin/sh
mallard-site-tool cache
mallard-site-tool html -o $1/
mallard-site-tool css -o $1/
mallard-site-tool js -o $1/
mallard-site-tool media -o $1/
./buildrng -o $1/
cp mallard-badge.png mallard-logo.svg mallard-logo-80.png duckbg.png swoop.png $1/
